environment          = "dev"
region               = "us-east-1"
state_bucket         = "tfstate-atlas"
domain_name          = "atlas-assistant.ds.io"
chat_model_size      = "large"
cors_origins          = "[\"https://adaptationatlas.github.io\"]"
cognito_redirect_urls = "[\"https://adaptationatlas.github.io/adaptation-atlas-assistant/\", \"http://localhost:5173\"]"
embeddings_directory = "/app/data/embeddings"
oidc_url             = "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_tnnHCVrfv/.well-known/openid-configuration"
oauth_client_id      = "7mg2hpfgj5qdpui6s6q601qn18"
tags = {
  project = "atlas-assistant"
  owner   = "orbaco"
  client  = "cgiar"
}
