repos:
  - repo: https://github.com/tsvikas/sync-with-uv
    rev: v0.4.0
    hooks:
      - id: sync-with-uv
  - repo: https://github.com/DetachHead/basedpyright-prek-mirror
    rev: 1.31.7
    hooks:
      - id: basedpyright
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
