[project]
name = "adaptation-atlas-co-pilot"
version = "0.0.1"
description = "Africa Agriculture Adaptation Atlas Co-Pilot "
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.13.2",
]
